objects:
    parent:
        paths:
        - database_id
        object:
            type: database_id
            database_id: null
    page_title:
        paths:
        - title[0].text.content
        object:
            title:
                - text:
                    content: null
    icon:
        paths:
        - external.url
        object:    
            external:
                url: null
    relation:
        paths:
        - relation[0].id
        object:
            relation:
                - id: null
    url:
        paths:
        - url
        object:
            url: null
    number:
        paths:
        - number
        object:
            number: null
    callout:
        paths:
        - callout.rich_text[0].text.content
        - callout.icon.external.url
        - callout.color
        object:
            type: callout
            callout:
                rich_text:
                    - type: text
                      text:
                        content: null
                      annotations:
                        bold: true
                icon:
                    type: external
                    external:
                        url: null
                color: null
    heading_1:
        paths:
        - heading_1.rich_text[0].text.content
        - heading_1.color
        - heading_1.is_toggleable
        object:
            type: heading_1
            heading_1:
                rich_text:
                    - type: text
                      text:
                        content: null
                      annotations:
                        bold: true
                color: null
                is_toggleable: true
    heading_2:
        paths:
        - heading_2.rich_text[0].text.content
        - heading_2.color
        - heading_2.is_toggleable
        object:
            type: heading_2
            heading_2:
                rich_text:
                    - type: text
                      text:
                        content: null
                      annotations:
                        bold: true
                color: null
                is_toggleable: true